services:
  - type: web
    name: remix-app
    env: node
    region: frankfurt
    plan: free
    branch: main
    healthCheckPath: /health
    buildCommand: npm i -g pnpm && pnpm i && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: ~16.15.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: main
          property: connectionString

databases:
  - name: main
    plan: free
